import {
  createContext,
  useContext,
  useEffect,
  useState,
  ReactNode,
} from "react";

// Podržani jezici
export type Language = "de" | "hr" | "en" | "it" | "sl";

// Prijevodi po jezicima
export const translations: Record<Language, Record<string, string>> = {
  de: {
    // Allgemeine Admin-Elemente
    "admin.general.uploading": "Wird hochgeladen...",
    "admin.product.preview": "Vorschau",
    
    // Navigacija
    "nav.home": "Startseite",
    "nav.products": "Produkte",
    "nav.about": "Über uns",
    "nav.contact": "Kontakt",
    "nav.cart": "Warenkorb",
    "nav.login": "Anmelden",
    "nav.account": "Mein Konto",
    "nav.admin": "Administration",
    "nav.logout": "Abmelden",
    "nav.allCategories": "Alle Kategorien",
    "nav.loadingCategories": "Kategorien werden geladen...",
    "nav.pictures": "Bilder",
    "nav.adminPanel": "Adminbereich",
    "nav.myProfile": "Mein Profil",
    "nav.myOrders": "Meine Bestellungen",

    // Admin Menü
    "admin.dashboard": "Dashboard",
    "admin.products": "Produkte",
    "admin.categories": "Kategorien",
    "admin.scents": "Düfte",
    "admin.colors": "Farben",
    "admin.collections": "Kollektionen",
    "admin.orders": "Bestellungen",
    "admin.invoices": "Rechnungen",
    "admin.users": "Benutzer",
    "admin.payments": "Zahlungen",
    "admin.panel": "Kerzenwelt Admin",
    "admin.delivery": "Liefereinstellungen",
    "admin.settings": "Einstellungen",
    "admin.pageSettings": "Seiteneinstellungen",
    "admin.contactSettings": "Kontakteinstellungen",
    "admin.documents": "Firmendokumente",
    "admin.notifications": "Benachrichtigungen",
    "admin.newOrder": "Neue Bestellung",
    "admin.statistics": "Statistiken",
    "admin.visits": "Seitenbesuche",
    "admin.addNew": "Neu hinzufügen",
    "admin.edit": "Bearbeiten",
    "admin.delete": "Löschen",
    "admin.save": "Speichern",
    "admin.cancel": "Abbrechen",
    "admin.actions": "Aktionen",
    "admin.status": "Status",
    "admin.active": "Aktiv",
    "admin.inactive": "Inaktiv",
    "admin.selectLanguage": "Sprache auswählen",
    
    // Admin Common Elements
    "admin.id": "ID",
    "admin.name": "Name",
    "admin.description": "Beschreibung",
    "admin.image": "Bild",
    "admin.price": "Preis",
    "admin.stock": "Lagerbestand",
    "admin.featured": "Hervorgehoben",
    "admin.category": "Kategorie",
    "admin.createdAt": "Erstellt am",
    "admin.updatedAt": "Aktualisiert am",
    "admin.search": "Suchen",
    "admin.filter": "Filtern",
    "admin.confirm": "Bestätigen",
    "admin.customer": "Kunde",
    "admin.date": "Datum",
    "admin.total": "Gesamt",
    "admin.quantity": "Menge",
    "admin.payment": "Zahlung",
    "admin.confirmDelete": "Löschen bestätigen",
    "admin.deleteWarning": "Möchten Sie dieses Element wirklich löschen? Diese Aktion kann nicht rückgängig gemacht werden.",
    
    // Admin Product Page
    "admin.productDetails": "Produktdetails",
    "admin.productName": "Produktname",
    "admin.productDescription": "Produktbeschreibung",
    "admin.productImage": "Produktbild",
    "admin.productPrice": "Produktpreis",
    "admin.productStock": "Produktlagerbestand",
    "admin.productCategory": "Produktkategorie",
    "admin.productActive": "Produkt aktiv",
    "admin.productFeatured": "Produkt hervorgehoben",
    "admin.productScents": "Produktdüfte",
    "admin.productColors": "Produktfarben",
    "admin.productDimensions": "Produktmaße",
    "admin.productWeight": "Produktgewicht",
    "admin.productMaterials": "Produktmaterialien",
    "admin.productUsage": "Produktverwendung",
    "admin.productMaintenance": "Produktpflege",
    "admin.uploadImage": "Bild hochladen",
    "admin.noScentsSelected": "Keine Düfte ausgewählt",
    "admin.noColorsSelected": "Keine Farben ausgewählt",
    "admin.chooseScents": "Düfte auswählen",
    "admin.chooseColors": "Farben auswählen",
    "admin.productSaved": "Produkt erfolgreich gespeichert",
    "admin.productDeleted": "Produkt erfolgreich gelöscht",
    "admin.product.featuredProduct": "Produkt auf Startseite hervorheben",
    "admin.product.productActive": "Produkt aktiv",
    "admin.product.productActiveHint": "(Wenn deaktiviert, ist das Produkt für Kunden nicht sichtbar)",
    "admin.product.saveChanges": "Änderungen speichern",
    "admin.product.createProduct": "Produkt erstellen",
    "admin.product.cancel": "Abbrechen",
    "admin.product.image": "Produktbild",
    "admin.product.url": "URL",
    "admin.product.upload": "Hochladen",
    "admin.product.imageUrlPlaceholder": "https://beispiel.com/bild.jpg",
    "admin.product.imageUrlDescription": "Geben Sie eine URL zu einem Bild ein",
    "admin.product.clickToUpload": "Klicken zum Hochladen",
    "admin.product.imageFormats": "JPG, PNG, GIF bis zu 5MB",
    "admin.product.imageResizeInfo": "Bilder werden automatisch auf 800x800px verkleinert",
    "admin.product.imageLoadingError": "Fehler beim Laden des Bildes",
    "admin.product.price": "Preis",
    "admin.product.pricePlaceholder": "Preis eingeben",
    "admin.product.stock": "Lagerbestand",
    "admin.product.stockPlaceholder": "Lagerbestand eingeben",
    "admin.product.description": "Beschreibung",
    "admin.product.descriptionPlaceholder": "Produktbeschreibung eingeben",
    "admin.product.name": "Name",
    "admin.product.namePlaceholder": "Produktname eingeben",
    "admin.product.dimensions": "Maße",
    "admin.product.dimensionsPlaceholder": "z.B. 10 x 5 x 3 cm",
    "admin.product.weight": "Gewicht",
    "admin.product.weightPlaceholder": "z.B. 250 g",
    "admin.product.materials": "Materialien",
    "admin.product.materialsPlaceholder": "z.B. Sojawachs, Baumwolldocht",
    "admin.product.usage": "Verwendung",
    "admin.product.usagePlaceholder": "Hinweise zur Verwendung",
    "admin.product.maintenance": "Pflege",
    "admin.product.maintenancePlaceholder": "Pflegehinweise",
    "admin.product.availableScents": "Verfügbare Düfte",
    "admin.product.selectScents": "Wählen Sie die Düfte aus, die für dieses Produkt verfügbar sein sollen",
    "admin.product.loadingScents": "Düfte werden geladen...",
    "admin.product.availableColors": "Verfügbare Farben",
    "admin.product.selectColors": "Wählen Sie die Farben aus, die für dieses Produkt verfügbar sein sollen",
    "admin.product.loadingColors": "Farben werden geladen...",
    "admin.product.enableColorSelection": "Farbauswahl aktivieren",
    "admin.product.enableMultipleColors": "Mehrfachauswahl von Farben ermöglichen",
    "admin.product.imagePreview": "Bildvorschau",
    "admin.product.category": "Kategorie",
    "admin.product.burnTime": "Brenndauer",
    "admin.product.instructions": "Anleitung",
    "admin.productsTitle": "Produkte",
    "admin.productsSubtitle": "Verwalten Sie Produkte in Ihrem Shop",
    "admin.productsList": "Produktliste",
    "admin.productsCount": "Produkte",
    "admin.product.imageColumn": "Bild",
    "admin.product.nameColumn": "Name",
    "admin.product.categoryColumn": "Kategorie",
    "admin.product.priceColumn": "Preis",
    "admin.product.stockColumn": "Bestand",
    "admin.product.statusColumn": "Status",
    "admin.product.actionsColumn": "Aktionen",
    "admin.product.inStock": "Auf Lager",
    "admin.product.active": "Aktiv",
    
    // Admin Orders Page
    "admin.orderDetails": "Bestelldetails",
    "admin.orderNumber": "Bestellnummer",
    "admin.orderDate": "Bestelldatum",
    "admin.orderStatus": "Bestellstatus",
    "admin.orderTotal": "Bestellsumme",
    "admin.orderItems": "Bestellartikel",
    "admin.orderCustomer": "Kunde",
    "admin.orderPayment": "Zahlungsmethode",
    "admin.orderShipping": "Versandadresse",
    "admin.orderBilling": "Rechnungsadresse",
    "admin.orderNotes": "Anmerkungen",
    "admin.updateOrderStatus": "Bestellstatus aktualisieren",
    "admin.generateInvoice": "Rechnung erstellen",
    "admin.pending": "Ausstehend",
    "admin.processing": "In Bearbeitung",
    "admin.shipped": "Versendet",
    "admin.delivered": "Geliefert",
    "admin.cancelled": "Storniert",
    "admin.statusUpdated": "Status erfolgreich aktualisiert",
    
    // Admin Invoice Page
    "admin.invoiceDetails": "Rechnungsdetails",
    "admin.invoiceNumber": "Rechnungsnummer",
    "admin.invoiceDate": "Rechnungsdatum",
    "admin.invoiceItems": "Rechnungsposten",
    "admin.subtotal": "Zwischensumme",
    "admin.tax": "Steuer",
    "admin.taxNumber": "Steuernummer",
    "admin.downloadInvoice": "Rechnung herunterladen",
    "admin.printInvoice": "Rechnung drucken",
    "admin.invoiceGenerated": "Rechnung erfolgreich erstellt",
    "admin.downloadFormat": "Download-Format",
    
    // Admin Users Page
    "admin.userDetails": "Benutzerdetails",
    "admin.username": "Benutzername",
    "admin.email": "E-Mail",
    "admin.password": "Passwort",
    "admin.firstName": "Vorname",
    "admin.lastName": "Nachname",
    "admin.address": "Adresse",
    "admin.city": "Stadt",
    "admin.postalCode": "Postleitzahl",
    "admin.country": "Land",
    "admin.phone": "Telefon",
    "admin.role": "Rolle",
    "admin.lastLogin": "Letzter Login",
    "admin.resetPassword": "Passwort zurücksetzen",
    "admin.userSaved": "Benutzer erfolgreich gespeichert",
    "admin.userDeleted": "Benutzer erfolgreich gelöscht",
    
    // Admin Settings Page
    "admin.generalSettings": "Allgemeine Einstellungen",
    "admin.shopName": "Shop-Name",
    "admin.shopLogo": "Shop-Logo",
    "admin.currency": "Währung",
    "admin.language": "Sprache",
    "admin.taxRate": "Steuersatz",
    "admin.contactEmail": "Kontakt-E-Mail",
    "admin.contactPhone": "Kontakttelefon",
    "admin.businessAddress": "Geschäftsadresse",
    "admin.socialLinks": "Social Media Links",
    "admin.metaTitle": "Meta-Titel",
    "admin.metaDescription": "Meta-Beschreibung",
    "admin.favicon": "Favicon",
    "admin.settingsSaved": "Einstellungen erfolgreich gespeichert",
    
    // Document Management
    "admin.uploadDocument": "Dokument hochladen",
    "admin.documentName": "Dokumentname",
    "admin.documentType": "Dokumenttyp",
    "admin.documentSize": "Dokumentgröße",
    "admin.documentDescription": "Dokumentbeschreibung",
    "admin.documentUploaded": "Dokument erfolgreich hochgeladen",
    "admin.documentDeleted": "Dokument erfolgreich gelöscht",
    "admin.download": "Herunterladen",

    // Naslovna stranica
    "home.featured": "Ausgewählte Produkte",
    "home.collections": "Kollektionen",
    "home.welcome": "Willkommen bei Kerzenwelt by Dani",
    "home.subtitle": "Handgemachte Kerzen mit natürlichen Zutaten",
    "home.shopNow": "Jetzt einkaufen",
    "home.categories": "Unsere Kategorien",
    "home.categoriesSubtitle":
      "Entdecken Sie unsere vielfältige Auswahl an handgefertigten Kerzen für jeden Anlass",
    "home.heroTitle": "Handgefertigte Kerzen für besondere Momente",
    "home.heroSubtitle":
      "Entdecken Sie unsere Kollektion von Premium-Duftkerzen, die mit Liebe hergestellt werden",
    "home.exploreCollection": "Kollektion erkunden",
    "home.aboutUs": "Über uns",
    "home.featuredSubtitle":
      "Unsere beliebtesten Produkte, die unsere Kunden lieben",
    "home.viewAllProducts": "Alle Produkte anzeigen",
    "home.errorLoading": "Beim Laden der Produkte ist ein Fehler aufgetreten.",
    "home.ourStory": "Unsere Geschichte",
    "home.storyDescription":
      "Jede unserer Kerzen wird mit Sorgfalt und Liebe hergestellt, wobei auf jedes Detail geachtet wird - von der Auswahl der besten Düfte bis zur Vollendung des ästhetischen Erscheinungsbildes. Wir sind stolz auf unser Handwerk und die Leidenschaft, mit der wir an jedes Produkt herangehen.",
    "home.naturalIngredients": "Natürliche Zutaten",
    "home.naturalIngredientsDesc":
      "Wir verwenden nur natürliches Sojawachs und ätherische Öle",
    "home.handmade": "Handgefertigt",
    "home.handmadeDesc": "Jede Kerze wird sorgfältig und von Hand hergestellt",
    "home.sustainability": "Nachhaltigkeit",
    "home.sustainabilityDesc": "Umweltfreundliche Verpackung und Materialien",
    "home.homeComfort": "Wohnkomfort",
    "home.homeComfortDesc":
      "Schaffen Sie eine gemütliche Atmosphäre in Ihrem Raum",
    "home.learnMore": "Mehr über uns erfahren",
    "home.autumnCollection": "Herbstkollektion",
    "home.autumnCollectionDesc":
      "Entdecken Sie unsere neue Kollektion von Herbstdüften. Warme und angenehme Düfte, die Ihr Zuhause an kühleren Tagen mit einem Gefühl von Gemütlichkeit und Wärme erfüllen.",
    "home.loading": "Laden...",
    "home.noProducts":
      "Dieser Kollektion wurden noch keine Produkte hinzugefügt.",
    "home.viewCollection": "Kollektion ansehen",

    // Proizvodi
    "product.addToCart": "In den Warenkorb",
    "product.selectScent": "Duft auswählen",
    "product.selectColor": "Farbe auswählen",
    "product.outOfStock": "Nicht auf Lager",
    "product.dimensions": "Abmessungen",
    "product.weight": "Gewicht",
    "product.burnTime": "Brenndauer",
    "product.materials": "Materialien",
    "product.instructions": "Anweisungen",
    "product.maintenance": "Pflege",

    // Košarica
    "cart.title": "Ihr Warenkorb",
    "cart.empty": "Ihr Warenkorb ist leer",
    "cart.continue": "Mit dem Einkaufen fortfahren",
    "cart.checkout": "Zur Kasse gehen",
    "cart.total": "Gesamtsumme",
    "cart.remove": "Entfernen",

    // Podnožje stranice
    "footer.about": "Über Kerzenwelt by Dani",
    "footer.about.text":
      "Handgefertigte Kerzen aus natürlichen Inhaltsstoffen. Von unserer Familie zu Ihrem Zuhause.",
    "footer.quickLinks": "Schnelllinks",
    "footer.customerSupport": "Kundenservice",
    "footer.contact": "Kontakt",
    "footer.followUs": "Folgen Sie uns",
    "footer.copyright": "Alle Rechte vorbehalten.",
    "footer.tagline":
      "Handgefertigte Kerzen aus natürlichen Inhaltsstoffen. Von unserer Familie zu Ihrem Zuhause.",
    "footer.myAccount": "Mein Konto",
    "footer.paymentMethods": "Zahlungsmethoden",

    // Testimonials
    "testimonials.title": "Was unsere Kunden sagen",
    "testimonials.subtitle": "Erfahrungen unserer zufriedenen Kunden",
    "testimonials.empty":
      "Wir haben noch keine Bewertungen. Seien Sie der Erste, der seine Erfahrung teilt!",
    "testimonials.browseProducts":
      "Produkte durchsuchen und eine Bewertung hinzufügen",
    "testimonials.loginToReview": "Einloggen und eine Bewertung hinzufügen",

    // Dialog components
    "dialog.areYouSure": "Sind Sie sicher?",
    "dialog.cannotUndo": "Diese Aktion kann nicht rückgängig gemacht werden.",
    "dialog.delete": "Löschen",
    "dialog.cancel": "Abbrechen",
    "dialog.confirm": "Bestätigen",

    // Newsletter
    "newsletter.title": "Abonnieren Sie unseren Newsletter",
    "newsletter.description":
      "Erfahren Sie als Erster von unseren neuen Produkten, Sonderangeboten und Rabatten. Abonnieren Sie unseren Newsletter und erhalten Sie 10% Rabatt auf Ihre erste Bestellung.",
    "newsletter.placeholder": "Ihre E-Mail-Adresse",
    "newsletter.button": "Abonnieren",
    "newsletter.loading": "Laden...",
    "newsletter.privacy":
      "Wir geben Ihre Daten niemals an Dritte weiter. Sie können sich jederzeit abmelden.",
    "newsletter.success":
      "Vielen Dank für Ihr Abonnement! Sie erhalten in Kürze unseren Newsletter.",
    "newsletter.error": "Bitte geben Sie Ihre E-Mail-Adresse ein.",
    
    // Admin panel
    "admin.backToStore": "Zurück zum Shop",
  },

  hr: {
    // Opći admin elementi
    "admin.general.uploading": "Učitavanje...",
    "admin.product.preview": "Pregled",
    
    // Navigacija
    "nav.home": "Početna",
    "nav.products": "Proizvodi",
    "nav.about": "O nama",
    "nav.contact": "Kontakt",
    "nav.cart": "Košarica",
    "nav.login": "Prijava",
    "nav.account": "Moj račun",
    "nav.admin": "Administracija",
    "nav.logout": "Odjava",
    "nav.adminPanel": "Admin meni",
    "nav.myProfile": "Moj Profil",
    "nav.myOrders": "Moje Narudzbe",
    "nav.allCategories": "Sve kategorije",
    "nav.loadingCategories": "Učitavanje kategorija...",
    "nav.pictures": "Slike",

    // Admin izbornik
    "admin.dashboard": "Nadzorna ploča",
    "admin.products": "Proizvodi",
    "admin.categories": "Kategorije",
    "admin.scents": "Mirisi",
    "admin.colors": "Boje",
    "admin.collections": "Kolekcije",
    "admin.orders": "Narudžbe",
    "admin.invoices": "Računi",
    "admin.users": "Korisnici",
    "admin.payments": "Plaćanja",
    "admin.panel": "Kerzenwelt Admin",
    "admin.delivery": "Postavke dostave",
    "admin.settings": "Postavke",
    "admin.pageSettings": "Postavke stranica",
    "admin.contactSettings": "Kontakt postavke",
    "admin.documents": "Dokumenti tvrtke",
    "admin.notifications": "Obavijesti",
    "admin.newOrder": "Nova narudžba",
    "admin.statistics": "Statistika",
    "admin.visits": "Posjete stranica",
    "admin.addNew": "Dodaj novi",
    "admin.edit": "Uredi",
    "admin.delete": "Obriši",
    "admin.save": "Spremi",
    "admin.cancel": "Odustani",
    "admin.actions": "Akcije",
    "admin.status": "Status",
    "admin.active": "Aktivno",
    "admin.inactive": "Neaktivno",
    "admin.selectLanguage": "Odaberi jezik",
    
    // Admin Common Elements
    "admin.id": "ID",
    "admin.name": "Naziv",
    "admin.description": "Opis",
    "admin.image": "Slika",
    "admin.price": "Cijena",
    "admin.stock": "Zaliha",
    "admin.featured": "Istaknuto",
    "admin.category": "Kategorija",
    "admin.createdAt": "Kreirano",
    "admin.updatedAt": "Ažurirano",
    "admin.search": "Pretraži",
    "admin.filter": "Filtriraj",
    "admin.confirm": "Potvrdi",
    "admin.customer": "Kupac",
    "admin.date": "Datum",
    "admin.total": "Ukupno",
    "admin.quantity": "Količina",
    "admin.payment": "Plaćanje",
    "admin.confirmDelete": "Potvrdi brisanje",
    "admin.deleteWarning": "Jeste li sigurni da želite izbrisati ovu stavku? Ova radnja ne može se poništiti.",
    
    // Admin Product Page
    "admin.productDetails": "Detalji proizvoda",
    "admin.productName": "Naziv proizvoda",
    "admin.productDescription": "Opis proizvoda",
    "admin.productImage": "Slika proizvoda",
    "admin.productPrice": "Cijena proizvoda",
    "admin.productStock": "Zaliha proizvoda",
    "admin.productCategory": "Kategorija proizvoda",
    "admin.productActive": "Proizvod aktivan",
    "admin.productFeatured": "Proizvod istaknut",
    "admin.productScents": "Mirisi proizvoda",
    "admin.productColors": "Boje proizvoda",
    "admin.productDimensions": "Dimenzije proizvoda",
    "admin.productWeight": "Težina proizvoda",
    "admin.productMaterials": "Materijali proizvoda",
    "admin.productUsage": "Upotreba proizvoda",
    "admin.productMaintenance": "Održavanje proizvoda",
    "admin.uploadImage": "Učitaj sliku",
    "admin.noScentsSelected": "Nema odabranih mirisa",
    "admin.noColorsSelected": "Nema odabranih boja",
    "admin.chooseScents": "Odaberi mirise",
    "admin.chooseColors": "Odaberi boje",
    "admin.productSaved": "Proizvod uspješno spremljen",
    "admin.productDeleted": "Proizvod uspješno obrisan",
    "admin.product.featuredProduct": "Istaknuti proizvod",
    "admin.product.productActive": "Proizvod aktivan",
    "admin.product.productActiveHint": "(Ako je isključeno, proizvod neće biti vidljiv kupcima)",
    "admin.product.saveChanges": "Spremi promjene",
    "admin.product.createProduct": "Kreiraj proizvod",
    "admin.product.cancel": "Poništi",
    "admin.product.image": "Slika proizvoda",
    "admin.product.url": "URL",
    "admin.product.upload": "Učitaj",
    "admin.product.imageUrlPlaceholder": "https://primjer.com/slika.jpg",
    "admin.product.imageUrlDescription": "Unesite URL do slike",
    "admin.product.clickToUpload": "Kliknite za učitavanje",
    "admin.product.imageFormats": "JPG, PNG, GIF do 5MB",
    "admin.product.imageResizeInfo": "Slike će automatski biti smanjene na 800x800px",
    "admin.product.imageLoadingError": "Greška pri učitavanju slike",
    "admin.product.price": "Cijena",
    "admin.product.pricePlaceholder": "Unesite cijenu",
    "admin.product.stock": "Zaliha",
    "admin.product.stockPlaceholder": "Unesite količinu na zalihi",
    "admin.product.description": "Opis",
    "admin.product.descriptionPlaceholder": "Unesite opis proizvoda",
    "admin.product.name": "Naziv",
    "admin.product.namePlaceholder": "Unesite naziv proizvoda",
    "admin.product.dimensions": "Dimenzije",
    "admin.product.dimensionsPlaceholder": "npr. 10 x 5 x 3 cm",
    "admin.product.weight": "Težina",
    "admin.product.weightPlaceholder": "npr. 250 g",
    "admin.product.materials": "Materijali",
    "admin.product.materialsPlaceholder": "npr. Sojin vosak, pamučni fitilj",
    "admin.product.usage": "Upotreba",
    "admin.product.usagePlaceholder": "Upute za upotrebu",
    "admin.product.maintenance": "Održavanje",
    "admin.product.maintenancePlaceholder": "Upute za održavanje",
    "admin.product.availableScents": "Dostupni mirisi",
    "admin.product.selectScents": "Odaberite mirise koji će biti dostupni za ovaj proizvod",
    "admin.product.loadingScents": "Učitavanje mirisa...",
    "admin.product.availableColors": "Dostupne boje",
    "admin.product.selectColors": "Odaberite boje koje će biti dostupne za ovaj proizvod",
    "admin.product.loadingColors": "Učitavanje boja...",
    "admin.product.enableColorSelection": "Omogući odabir boja",
    "admin.product.enableMultipleColors": "Omogući odabir više boja",
    "admin.product.imagePreview": "Pregled slike",
    "admin.product.category": "Kategorija",
    "admin.product.burnTime": "Vrijeme gorenja",
    "admin.product.instructions": "Upute",
    "admin.productsTitle": "Proizvodi",
    "admin.productsSubtitle": "Upravljajte proizvodima u trgovini",
    "admin.productsList": "Lista proizvoda",
    "admin.productsCount": "proizvoda",
    "admin.product.imageColumn": "Slika",
    "admin.product.nameColumn": "Naziv",
    "admin.product.categoryColumn": "Kategorija",
    "admin.product.priceColumn": "Cijena",
    "admin.product.stockColumn": "Zaliha",
    "admin.product.statusColumn": "Status",
    "admin.product.actionsColumn": "Akcije",
    "admin.product.inStock": "Na zalihi",
    "admin.product.active": "Aktivan",
    
    // Admin Orders Page
    "admin.orderDetails": "Detalji narudžbe",
    "admin.orderNumber": "Broj narudžbe",
    "admin.orderDate": "Datum narudžbe",
    "admin.orderStatus": "Status narudžbe",
    "admin.orderTotal": "Ukupni iznos narudžbe",
    "admin.orderItems": "Stavke narudžbe",
    "admin.orderCustomer": "Kupac",
    "admin.orderPayment": "Način plaćanja",
    "admin.orderShipping": "Adresa dostave",
    "admin.orderBilling": "Adresa naplate",
    "admin.orderNotes": "Napomene",
    "admin.updateOrderStatus": "Ažuriraj status narudžbe",
    "admin.generateInvoice": "Generiraj račun",
    "admin.pending": "Na čekanju",
    "admin.processing": "U obradi",
    "admin.shipped": "Poslano",
    "admin.delivered": "Dostavljeno",
    "admin.cancelled": "Otkazano",
    "admin.statusUpdated": "Status uspješno ažuriran",
    
    // Admin Invoice Page
    "admin.invoiceDetails": "Detalji računa",
    "admin.invoiceNumber": "Broj računa",
    "admin.invoiceDate": "Datum računa",
    "admin.invoiceItems": "Stavke računa",
    "admin.subtotal": "Međuzbroj",
    "admin.tax": "Porez",
    "admin.taxNumber": "Porezni broj",
    "admin.downloadInvoice": "Preuzmi račun",
    "admin.printInvoice": "Ispiši račun",
    "admin.invoiceGenerated": "Račun uspješno generiran",
    "admin.downloadFormat": "Format preuzimanja",
    
    // Admin Users Page
    "admin.userDetails": "Detalji korisnika",
    "admin.username": "Korisničko ime",
    "admin.email": "E-mail",
    "admin.password": "Lozinka",
    "admin.firstName": "Ime",
    "admin.lastName": "Prezime",
    "admin.address": "Adresa",
    "admin.city": "Grad",
    "admin.postalCode": "Poštanski broj",
    "admin.country": "Država",
    "admin.phone": "Telefon",
    "admin.role": "Uloga",
    "admin.lastLogin": "Zadnja prijava",
    "admin.resetPassword": "Resetiraj lozinku",
    "admin.userSaved": "Korisnik uspješno spremljen",
    "admin.userDeleted": "Korisnik uspješno obrisan",
    
    // Admin Settings Page
    "admin.generalSettings": "Opće postavke",
    "admin.shopName": "Naziv trgovine",
    "admin.shopLogo": "Logo trgovine",
    "admin.currency": "Valuta",
    "admin.language": "Jezik",
    "admin.taxRate": "Porezna stopa",
    "admin.contactEmail": "Kontakt e-mail",
    "admin.contactPhone": "Kontakt telefon",
    "admin.businessAddress": "Poslovna adresa",
    "admin.socialLinks": "Društvene mreže",
    "admin.metaTitle": "Meta naslov",
    "admin.metaDescription": "Meta opis",
    "admin.favicon": "Favicon",
    "admin.settingsSaved": "Postavke uspješno spremljene",
    
    // Document Management
    "admin.uploadDocument": "Učitaj dokument",
    "admin.documentName": "Naziv dokumenta",
    "admin.documentType": "Vrsta dokumenta",
    "admin.documentSize": "Veličina dokumenta",
    "admin.documentDescription": "Opis dokumenta",
    "admin.documentUploaded": "Dokument uspješno učitan",
    "admin.documentDeleted": "Dokument uspješno obrisan",
    "admin.download": "Preuzmi",

    // Naslovna stranica
    "home.featured": "Izdvojeni proizvodi",
    "home.collections": "Kolekcije",
    "home.welcome": "Dobrodošli u Kerzenwelt by Dani",
    "home.subtitle": "Ručno izrađene svijeće od prirodnih sastojaka",
    "home.shopNow": "Kupite odmah",
    "home.categories": "Naše kategorije",
    "home.categoriesSubtitle":
      "Istražite našu bogatu ponudu ručno izrađenih svijeća za svaku priliku",
    "home.heroTitle": "Ručno izrađene svijeće za posebne trenutke",
    "home.heroSubtitle":
      "Otkrijte našu kolekciju premium mirisnih svijeća izrađenih s ljubavlju",
    "home.exploreCollection": "Istraži kolekciju",
    "home.aboutUs": "O nama",
    "home.featuredSubtitle":
      "Naši najpopularniji proizvodi koje naši kupci vole",
    "home.viewAllProducts": "Vidi sve proizvode",
    "home.errorLoading": "Došlo je do greške prilikom učitavanja proizvoda.",
    "home.ourStory": "Naša priča",
    "home.storyDescription":
      "Svaka naša svijeća je izrađena s pažnjom i ljubavlju, pazeći na svaki detalj - od odabira najboljih mirisa do dovršavanja estetskog izgleda. Ponosni smo na naš obrt i strast kojom pristupamo svakom proizvodu.",
    "home.naturalIngredients": "Prirodni sastojci",
    "home.naturalIngredientsDesc":
      "Koristimo samo prirodni sojin vosak i esencijalna ulja",
    "home.handmade": "Ručna izrada",
    "home.handmadeDesc": "Svaka svijeća je pažljivo i ručno izrađena",
    "home.sustainability": "Održivost",
    "home.sustainabilityDesc": "Ekološki prihvatljiva ambalaža i materijali",
    "home.homeComfort": "Udobnost doma",
    "home.homeComfortDesc": "Stvorite ugodnu atmosferu u svom prostoru",
    "home.learnMore": "Saznajte više o nama",
    "home.autumnCollection": "Jesenska kolekcija",
    "home.autumnCollectionDesc":
      "Otkrijte našu novu kolekciju jesenskih mirisa. Topli i ugodni mirisi koji će vaš dom ispuniti osjećajem udobnosti i topline tijekom hladnijih dana.",
    "home.loading": "Učitavanje...",
    "home.noProducts": "Još nisu dodani proizvodi u ovu kolekciju.",
    "home.viewCollection": "Pregledaj kolekciju",

    // Proizvodi
    "product.addToCart": "Dodaj u košaricu",
    "product.selectScent": "Odaberite miris",
    "product.selectColor": "Odaberite boju",
    "product.outOfStock": "Nije dostupno",
    "product.dimensions": "Dimenzije",
    "product.weight": "Težina",
    "product.burnTime": "Vrijeme gorenja",
    "product.materials": "Materijali",
    "product.instructions": "Upute za korištenje",
    "product.maintenance": "Održavanje",

    // Košarica
    "cart.title": "Vaša košarica",
    "cart.empty": "Vaša košarica je prazna",
    "cart.continue": "Nastavi s kupovinom",
    "cart.checkout": "Završi narudžbu",
    "cart.total": "Ukupno",
    "cart.remove": "Ukloni",

    // Podnožje stranice
    "footer.about": "O Kerzenwelt by Dani",
    "footer.about.text":
      "Ručno izrađene svijeće od prirodnih sastojaka. Od naše obitelji do vašeg doma.",
    "footer.quickLinks": "Brzi linkovi",
    "footer.customerSupport": "Korisnička podrška",
    "footer.contact": "Kontakt",
    "footer.followUs": "Pratite nas",
    "footer.copyright": "Sva prava pridržana.",
    "footer.tagline":
      "Ručno izrađene svijeće od prirodnih sastojaka. Od naše obitelji do vašeg doma.",
    "footer.myAccount": "Moj račun",
    "footer.paymentMethods": "Načini plaćanja",

    // Testimonials
    "testimonials.title": "Što kažu naši kupci",
    "testimonials.subtitle": "Iskustva naših zadovoljnih kupaca",
    "testimonials.empty":
      "Trenutno nemamo recenzija. Budite prvi koji će ostaviti svoje iskustvo!",
    "testimonials.browseProducts": "Pregledaj proizvode i dodaj recenziju",
    "testimonials.loginToReview": "Prijavi se i dodaj recenziju",

    // Dialog komponente
    "dialog.areYouSure": "Jeste li sigurni?",
    "dialog.cannotUndo": "Ova radnja se ne može poništiti.",
    "dialog.delete": "Izbriši",
    "dialog.cancel": "Odustani",
    "dialog.confirm": "Potvrdi",

    // Newsletter
    "newsletter.title": "Pretplatite se na novosti",
    "newsletter.description":
      "Budite prvi koji će saznati o našim novim proizvodima, posebnim ponudama i popustima. Pretplatite se na naš newsletter i dobijte 10% popusta na vašu prvu narudžbu.",
    "newsletter.placeholder": "Vaša email adresa",
    "newsletter.button": "Pretplatite se",
    "newsletter.loading": "Učitavanje...",
    "newsletter.privacy":
      "Nećemo dijeliti vaše podatke s trećim stranama. Možete se odjaviti u bilo kojem trenutku.",
    "newsletter.success":
      "Hvala na prijavi! Uskoro ćete primiti naš newsletter.",
    "newsletter.error": "Molimo unesite vašu email adresu.",
    
    // Admin panel
    "admin.backToStore": "Natrag na trgovinu",
  },

  en: {
    // General admin elements
    "admin.general.uploading": "Uploading...",
    "admin.product.preview": "Preview",
    "admin.product.imagePreview": "Image preview",
    
    // Navigation
    "nav.home": "Home",
    "nav.products": "Products",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.cart": "Cart",
    "nav.login": "Login",
    "nav.account": "My Account",
    "nav.admin": "Admin",
    "nav.adminPanel": "Admin Panel",
    "nav.myProfile": "My Profile",
    "nav.myOrders": "My Orders",
    "nav.logout": "Logout",
    "nav.allCategories": "All Categories",
    "nav.loadingCategories": "Loading categories...",
    "nav.pictures": "Pictures",

    // Admin menu
    "admin.dashboard": "Dashboard",
    "admin.products": "Products",
    "admin.categories": "Categories",
    "admin.scents": "Scents",
    "admin.colors": "Colors",
    "admin.collections": "Collections",
    "admin.orders": "Orders",
    "admin.invoices": "Invoices",
    "admin.users": "Users",
    "admin.payments": "Payments",
    "admin.panel": "Kerzenwelt Admin",
    "admin.delivery": "Delivery Settings",
    "admin.settings": "Settings",
    "admin.pageSettings": "Page Settings",
    "admin.contactSettings": "Contact Settings",
    "admin.documents": "Company Documents",
    "admin.notifications": "Notifications",
    "admin.newOrder": "New Order",
    "admin.statistics": "Statistics",
    "admin.visits": "Page Visits",
    "admin.addNew": "Add New",
    "admin.edit": "Edit",
    "admin.delete": "Delete",
    "admin.save": "Save",
    "admin.cancel": "Cancel",
    "admin.actions": "Actions",
    "admin.status": "Status",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.selectLanguage": "Select Language",
    
    // Admin Common Elements
    "admin.id": "ID",
    "admin.name": "Name",
    "admin.description": "Description",
    "admin.image": "Image",
    "admin.price": "Price",
    "admin.stock": "Stock",
    "admin.featured": "Featured",
    "admin.category": "Category",
    "admin.createdAt": "Created At",
    "admin.updatedAt": "Updated At",
    "admin.search": "Search",
    "admin.filter": "Filter",
    "admin.confirm": "Confirm",
    "admin.customer": "Customer",
    "admin.date": "Date",
    "admin.total": "Total",
    "admin.quantity": "Quantity",
    "admin.payment": "Payment",
    "admin.confirmDelete": "Confirm Delete",
    "admin.deleteWarning": "Are you sure you want to delete this item? This action cannot be undone.",
    
    // Admin Product Page
    "admin.productDetails": "Product Details",
    "admin.productName": "Product Name",
    "admin.productDescription": "Product Description",
    "admin.productImage": "Product Image",
    "admin.productPrice": "Product Price",
    "admin.productStock": "Product Stock",
    "admin.productCategory": "Product Category",
    "admin.productActive": "Product Active",
    "admin.productFeatured": "Product Featured",
    "admin.productScents": "Product Scents",
    "admin.productColors": "Product Colors",
    "admin.productDimensions": "Product Dimensions",
    "admin.productWeight": "Product Weight",
    "admin.productMaterials": "Product Materials",
    "admin.productUsage": "Product Usage",
    "admin.productMaintenance": "Product Maintenance",
    "admin.uploadImage": "Upload Image",
    "admin.noScentsSelected": "No Scents Selected",
    "admin.noColorsSelected": "No Colors Selected",
    "admin.chooseScents": "Choose Scents",
    "admin.chooseColors": "Choose Colors",
    "admin.productSaved": "Product Successfully Saved",
    "admin.productDeleted": "Product Successfully Deleted",
    "admin.product.featuredProduct": "Featured on Homepage",
    "admin.product.productActive": "Product Active",
    "admin.product.productActiveHint": "(If disabled, the product will not be visible to customers)",
    "admin.product.saveChanges": "Save Changes",
    "admin.product.createProduct": "Create Product",
    "admin.product.cancel": "Cancel",
    "admin.product.image": "Product Image",
    "admin.product.url": "URL",
    "admin.product.upload": "Upload",
    "admin.product.imageUrlPlaceholder": "https://example.com/image.jpg",
    "admin.product.imageUrlDescription": "Enter a URL to an image",
    "admin.product.clickToUpload": "Click to upload",
    "admin.product.imageFormats": "JPG, PNG, GIF up to 5MB",
    "admin.product.imageResizeInfo": "Images will be automatically resized to 800x800px",
    "admin.product.imageLoadingError": "Error loading image",
    "admin.product.price": "Price",
    "admin.product.pricePlaceholder": "Enter price",
    "admin.product.stock": "Stock",
    "admin.product.stockPlaceholder": "Enter stock quantity",
    "admin.product.description": "Description",
    "admin.product.descriptionPlaceholder": "Enter product description",
    "admin.product.name": "Name",
    "admin.product.namePlaceholder": "Enter product name",
    "admin.product.dimensions": "Dimensions",
    "admin.product.dimensionsPlaceholder": "e.g. 10 x 5 x 3 cm",
    "admin.product.weight": "Weight",
    "admin.product.weightPlaceholder": "e.g. 250 g",
    "admin.product.materials": "Materials",
    "admin.product.materialsPlaceholder": "e.g. Soy wax, cotton wick",
    "admin.product.usage": "Usage",
    "admin.product.usagePlaceholder": "Usage instructions",
    "admin.product.maintenance": "Maintenance",
    "admin.product.maintenancePlaceholder": "Maintenance instructions",
    "admin.product.availableScents": "Available Scents",
    "admin.product.selectScents": "Select the scents that will be available for this product",
    "admin.product.loadingScents": "Loading scents...",
    "admin.product.availableColors": "Available Colors",
    "admin.product.selectColors": "Select the colors that will be available for this product",
    "admin.product.loadingColors": "Loading colors...",
    "admin.product.enableColorSelection": "Enable color selection",
    "admin.product.enableMultipleColors": "Enable multiple color selection",
    "admin.product.imagePreview": "Image preview",
    "admin.product.category": "Category",
    "admin.product.burnTime": "Burn Time",
    "admin.product.instructions": "Instructions",
    "admin.productsTitle": "Products",
    "admin.productsSubtitle": "Manage products in your store",
    "admin.productsList": "Product List",
    "admin.productsCount": "products",
    "admin.product.imageColumn": "Image",
    "admin.product.nameColumn": "Name",
    "admin.product.categoryColumn": "Category",
    "admin.product.priceColumn": "Price",
    "admin.product.stockColumn": "Stock",
    "admin.product.statusColumn": "Status",
    "admin.product.actionsColumn": "Actions",
    "admin.product.inStock": "In Stock",
    "admin.product.active": "Active",
    
    // Admin Orders Page
    "admin.orderDetails": "Order Details",
    "admin.orderNumber": "Order Number",
    "admin.orderDate": "Order Date",
    "admin.orderStatus": "Order Status",
    "admin.orderTotal": "Order Total",
    "admin.orderItems": "Order Items",
    "admin.orderCustomer": "Customer",
    "admin.orderPayment": "Payment Method",
    "admin.orderShipping": "Shipping Address",
    "admin.orderBilling": "Billing Address",
    "admin.orderNotes": "Notes",
    "admin.updateOrderStatus": "Update Order Status",
    "admin.generateInvoice": "Generate Invoice",
    "admin.pending": "Pending",
    "admin.processing": "Processing",
    "admin.shipped": "Shipped",
    "admin.delivered": "Delivered",
    "admin.cancelled": "Cancelled",
    "admin.statusUpdated": "Status Successfully Updated",
    
    // Admin Invoice Page
    "admin.invoiceDetails": "Invoice Details",
    "admin.invoiceNumber": "Invoice Number",
    "admin.invoiceDate": "Invoice Date",
    "admin.invoiceItems": "Invoice Items",
    "admin.subtotal": "Subtotal",
    "admin.tax": "Tax",
    "admin.taxNumber": "Tax Number",
    "admin.downloadInvoice": "Download Invoice",
    "admin.printInvoice": "Print Invoice",
    "admin.invoiceGenerated": "Invoice Successfully Generated",
    "admin.downloadFormat": "Download Format",
    
    // Admin Users Page
    "admin.userDetails": "User Details",
    "admin.username": "Username",
    "admin.email": "Email",
    "admin.password": "Password",
    "admin.firstName": "First Name",
    "admin.lastName": "Last Name",
    "admin.address": "Address",
    "admin.city": "City",
    "admin.postalCode": "Postal Code",
    "admin.country": "Country",
    "admin.phone": "Phone",
    "admin.role": "Role",
    "admin.lastLogin": "Last Login",
    "admin.resetPassword": "Reset Password",
    "admin.userSaved": "User Successfully Saved",
    "admin.userDeleted": "User Successfully Deleted",
    
    // Admin Settings Page
    "admin.generalSettings": "General Settings",
    "admin.shopName": "Shop Name",
    "admin.shopLogo": "Shop Logo",
    "admin.currency": "Currency",
    "admin.language": "Language",
    "admin.taxRate": "Tax Rate",
    "admin.contactEmail": "Contact Email",
    "admin.contactPhone": "Contact Phone",
    "admin.businessAddress": "Business Address",
    "admin.socialLinks": "Social Media Links",
    "admin.metaTitle": "Meta Title",
    "admin.metaDescription": "Meta Description",
    "admin.favicon": "Favicon",
    "admin.settingsSaved": "Settings Successfully Saved",
    
    // Document Management
    "admin.uploadDocument": "Upload Document",
    "admin.documentName": "Document Name",
    "admin.documentType": "Document Type",
    "admin.documentSize": "Document Size",
    "admin.documentDescription": "Document Description",
    "admin.documentUploaded": "Document Successfully Uploaded",
    "admin.documentDeleted": "Document Successfully Deleted",
    "admin.download": "Download",

    // Dialog components
    "dialog.areYouSure": "Are you sure?",
    "dialog.cannotUndo": "This action cannot be undone.",
    "dialog.delete": "Delete",
    "dialog.cancel": "Cancel",
    "dialog.confirm": "Confirm",

    // Home page
    "home.featured": "Featured Products",
    "home.collections": "Collections",
    "home.welcome": "Welcome to Kerzenwelt by Dani",
    "home.subtitle": "Handmade candles with natural ingredients",
    "home.shopNow": "Shop Now",
    "home.categories": "Our Categories",
    "home.categoriesSubtitle":
      "Explore our rich selection of handmade candles for every occasion",
    "home.heroTitle": "Handmade Candles for Special Moments",
    "home.heroSubtitle":
      "Discover our collection of premium scented candles made with love",
    "home.exploreCollection": "Explore Collection",
    "home.aboutUs": "About Us",
    "home.featuredSubtitle":
      "Our most popular products that our customers love",
    "home.viewAllProducts": "View all products",
    "home.errorLoading": "An error occurred while loading products.",
    "home.ourStory": "Our Story",
    "home.storyDescription":
      "Each of our candles is crafted with care and love, paying attention to every detail - from selecting the best scents to finishing the aesthetic appearance. We take pride in our craft and the passion with which we approach every product.",
    "home.naturalIngredients": "Natural Ingredients",
    "home.naturalIngredientsDesc":
      "We use only natural soy wax and essential oils",
    "home.handmade": "Handmade",
    "home.handmadeDesc": "Each candle is carefully and handcrafted",
    "home.sustainability": "Sustainability",
    "home.sustainabilityDesc":
      "Environmentally friendly packaging and materials",
    "home.homeComfort": "Home Comfort",
    "home.homeComfortDesc": "Create a cozy atmosphere in your space",
    "home.learnMore": "Learn more about us",
    "home.autumnCollection": "Autumn Collection",
    "home.autumnCollectionDesc":
      "Discover our new collection of autumn scents. Warm and pleasant fragrances that will fill your home with a sense of comfort and warmth during the cooler days.",
    "home.loading": "Loading...",
    "home.noProducts": "No products have been added to this collection yet.",
    "home.viewCollection": "View collection",

    // Products
    "product.addToCart": "Add to Cart",
    "product.selectScent": "Select Scent",
    "product.selectColor": "Select Color",
    "product.outOfStock": "Out of Stock",
    "product.dimensions": "Dimensions",
    "product.weight": "Weight",
    "product.burnTime": "Burn Time",
    "product.materials": "Materials",
    "product.instructions": "Instructions",
    "product.maintenance": "Maintenance",

    // Cart
    "cart.title": "Your Cart",
    "cart.empty": "Your cart is empty",
    "cart.continue": "Continue Shopping",
    "cart.checkout": "Checkout",
    "cart.total": "Total",
    "cart.remove": "Remove",

    // Footer
    "footer.about": "About Kerzenwelt by Dani",
    "footer.about.text":
      "Handmade candles with natural ingredients. From our family to your home.",
    "footer.quickLinks": "Quick Links",
    "footer.customerSupport": "Customer Support",
    "footer.contact": "Contact",
    "footer.followUs": "Follow Us",
    "footer.copyright": "All rights reserved.",
    "footer.tagline":
      "Handmade candles with natural ingredients. From our family to your home.",
    "footer.myAccount": "My Account",
    "footer.paymentMethods": "Payment Methods",

    // Testimonials
    "testimonials.title": "What Our Customers Say",
    "testimonials.subtitle": "Experiences from our satisfied customers",
    "testimonials.empty":
      "We don't have any reviews yet. Be the first to share your experience!",
    "testimonials.browseProducts": "Browse products and add a review",
    "testimonials.loginToReview": "Log in and add a review",

    // Newsletter
    "newsletter.title": "Subscribe to our newsletter",
    "newsletter.description":
      "Be the first to know about our new products, special offers and discounts. Subscribe to our newsletter and get 10% off your first order.",
    "newsletter.placeholder": "Your email address",
    "newsletter.button": "Subscribe",
    "newsletter.loading": "Loading...",
    "newsletter.privacy":
      "We'll never share your data with third parties. You can unsubscribe at any time.",
    "newsletter.success":
      "Thank you for subscribing! You'll receive our newsletter soon.",
    "newsletter.error": "Please enter your email address.",
    
    // Admin panel
    "admin.backToStore": "Back to store",
  },

  it: {
    // Elementi amministrativi generali
    "admin.general.uploading": "Caricamento in corso...",
    "admin.product.preview": "Anteprima",
    
    // Navigazione
    "nav.home": "Home",
    "nav.products": "Prodotti",
    "nav.about": "Chi siamo",
    "nav.contact": "Contatti",
    "nav.cart": "Carrello",
    "nav.login": "Accedi",
    "nav.account": "Il mio account",
    "nav.admin": "Amministrazione",
    "nav.logout": "Esci",
    "nav.allCategories": "Tutte le categorie",
    "nav.loadingCategories": "Caricamento categorie...",
    "nav.pictures": "Immagini",

    // Menu amministrazione
    "admin.dashboard": "Dashboard",
    "admin.products": "Prodotti",
    "admin.categories": "Categorie",
    "admin.scents": "Profumi",
    "admin.colors": "Colori",
    "admin.collections": "Collezioni",
    "admin.orders": "Ordini",
    "admin.invoices": "Fatture",
    "admin.users": "Utenti",
    "admin.payments": "Pagamenti",
    "admin.panel": "Kerzenwelt Admin",
    "admin.delivery": "Impostazioni di consegna",
    "admin.settings": "Impostazioni",
    "admin.pageSettings": "Impostazioni pagina",
    "admin.contactSettings": "Impostazioni contatti",
    "admin.documents": "Documenti aziendali",
    "admin.notifications": "Notifiche",
    "admin.newOrder": "Nuovo ordine",
    "admin.statistics": "Statistiche",
    "admin.visits": "Visite pagina",
    "admin.addNew": "Aggiungi nuovo",
    "admin.edit": "Modifica",
    "admin.delete": "Elimina",
    "admin.save": "Salva",
    "admin.cancel": "Annulla",
    "admin.actions": "Azioni",
    "admin.status": "Stato",
    "admin.active": "Attivo",
    "admin.inactive": "Inattivo",
    "admin.selectLanguage": "Seleziona lingua",
    
    // Admin Common Elements
    "admin.id": "ID",
    "admin.name": "Nome",
    "admin.description": "Descrizione",
    "admin.image": "Immagine",
    "admin.price": "Prezzo",
    "admin.stock": "Scorta",
    "admin.featured": "In evidenza",
    "admin.category": "Categoria",
    "admin.createdAt": "Creato il",
    "admin.updatedAt": "Aggiornato il",
    "admin.search": "Cerca",
    "admin.filter": "Filtra",
    "admin.confirm": "Conferma",
    "admin.customer": "Cliente",
    "admin.date": "Data",
    "admin.total": "Totale",
    "admin.quantity": "Quantità",
    "admin.payment": "Pagamento",
    "admin.confirmDelete": "Conferma eliminazione",
    "admin.deleteWarning": "Sei sicuro di voler eliminare questo elemento? Questa azione non può essere annullata.",
    
    // Admin Product Page
    "admin.productDetails": "Dettagli prodotto",
    "admin.productName": "Nome prodotto",
    "admin.productDescription": "Descrizione prodotto",
    "admin.productImage": "Immagine prodotto",
    "admin.productPrice": "Prezzo prodotto",
    "admin.productStock": "Scorta prodotto",
    "admin.productCategory": "Categoria prodotto",
    "admin.productActive": "Prodotto attivo",
    "admin.productFeatured": "Prodotto in evidenza",
    "admin.productScents": "Profumi prodotto",
    "admin.productColors": "Colori prodotto",
    "admin.productDimensions": "Dimensioni prodotto",
    "admin.productWeight": "Peso prodotto",
    "admin.productMaterials": "Materiali prodotto",
    "admin.productUsage": "Utilizzo prodotto",
    "admin.productMaintenance": "Manutenzione prodotto",
    "admin.uploadImage": "Carica immagine",
    "admin.noScentsSelected": "Nessun profumo selezionato",
    "admin.noColorsSelected": "Nessun colore selezionato",
    "admin.chooseScents": "Scegli profumi",
    "admin.chooseColors": "Scegli colori",
    "admin.productSaved": "Prodotto salvato con successo",
    "admin.productDeleted": "Prodotto eliminato con successo",
    "admin.product.featuredProduct": "In evidenza sulla homepage",
    "admin.product.productActive": "Prodotto attivo",
    "admin.product.productActiveHint": "(Se disabilitato, il prodotto non sarà visibile ai clienti)",
    "admin.product.saveChanges": "Salva modifiche",
    "admin.product.createProduct": "Crea prodotto",
    "admin.product.cancel": "Annulla",
    "admin.product.image": "Immagine prodotto",
    "admin.product.url": "URL",
    "admin.product.upload": "Carica",
    "admin.product.imageUrlPlaceholder": "https://esempio.com/immagine.jpg",
    "admin.product.imageUrlDescription": "Inserisci l'URL di un'immagine",
    "admin.product.clickToUpload": "Clicca per caricare",
    "admin.product.imageFormats": "JPG, PNG, GIF fino a 5MB",
    "admin.product.imageResizeInfo": "Le immagini saranno automaticamente ridimensionate a 800x800px",
    "admin.product.imageLoadingError": "Errore durante il caricamento dell'immagine",
    "admin.product.price": "Prezzo",
    "admin.product.pricePlaceholder": "Inserisci prezzo",
    "admin.product.stock": "Scorta",
    "admin.product.stockPlaceholder": "Inserisci quantità disponibile",
    "admin.product.description": "Descrizione",
    "admin.product.descriptionPlaceholder": "Inserisci descrizione del prodotto",
    "admin.product.name": "Nome",
    "admin.product.namePlaceholder": "Inserisci nome del prodotto",
    "admin.product.dimensions": "Dimensioni",
    "admin.product.dimensionsPlaceholder": "es. 10 x 5 x 3 cm",
    "admin.product.weight": "Peso",
    "admin.product.weightPlaceholder": "es. 250 g",
    "admin.product.materials": "Materiali",
    "admin.product.materialsPlaceholder": "es. Cera di soia, stoppino di cotone",
    "admin.product.usage": "Utilizzo",
    "admin.product.usagePlaceholder": "Istruzioni per l'uso",
    "admin.product.maintenance": "Manutenzione",
    "admin.product.maintenancePlaceholder": "Istruzioni per la manutenzione",
    "admin.product.availableScents": "Profumi disponibili",
    "admin.product.selectScents": "Seleziona i profumi che saranno disponibili per questo prodotto",
    "admin.product.loadingScents": "Caricamento profumi...",
    "admin.product.availableColors": "Colori disponibili",
    "admin.product.selectColors": "Seleziona i colori che saranno disponibili per questo prodotto",
    "admin.product.loadingColors": "Caricamento colori...",
    "admin.product.enableColorSelection": "Abilita selezione colori",
    "admin.product.enableMultipleColors": "Abilita selezione di più colori",
    "admin.product.imagePreview": "Anteprima immagine",
    "admin.product.category": "Categoria",
    "admin.product.burnTime": "Tempo di combustione",
    "admin.product.instructions": "Istruzioni",
    "admin.productsTitle": "Prodotti",
    "admin.productsSubtitle": "Gestisci i prodotti nel tuo negozio",
    "admin.productsList": "Elenco prodotti",
    "admin.productsCount": "prodotti",
    "admin.product.imageColumn": "Immagine",
    "admin.product.nameColumn": "Nome",
    "admin.product.categoryColumn": "Categoria",
    "admin.product.priceColumn": "Prezzo",
    "admin.product.stockColumn": "Disponibilità",
    "admin.product.statusColumn": "Stato",
    "admin.product.actionsColumn": "Azioni",
    "admin.product.inStock": "Disponibile",
    "admin.product.active": "Attivo",
    
    // Admin Orders Page
    "admin.orderDetails": "Dettagli ordine",
    "admin.orderNumber": "Numero ordine",
    "admin.orderDate": "Data ordine",
    "admin.orderStatus": "Stato ordine",
    "admin.orderTotal": "Totale ordine",
    "admin.orderItems": "Articoli ordine",
    "admin.orderCustomer": "Cliente",
    "admin.orderPayment": "Metodo di pagamento",
    "admin.orderShipping": "Indirizzo di spedizione",
    "admin.orderBilling": "Indirizzo di fatturazione",
    "admin.orderNotes": "Note",
    "admin.updateOrderStatus": "Aggiorna stato ordine",
    "admin.generateInvoice": "Genera fattura",
    "admin.pending": "In attesa",
    "admin.processing": "In elaborazione",
    "admin.shipped": "Spedito",
    "admin.delivered": "Consegnato",
    "admin.cancelled": "Annullato",
    "admin.statusUpdated": "Stato aggiornato con successo",
    
    // Admin Invoice Page
    "admin.invoiceDetails": "Dettagli fattura",
    "admin.invoiceNumber": "Numero fattura",
    "admin.invoiceDate": "Data fattura",
    "admin.invoiceItems": "Articoli fattura",
    "admin.subtotal": "Subtotale",
    "admin.tax": "Imposta",
    "admin.taxNumber": "Numero fiscale",
    "admin.downloadInvoice": "Scarica fattura",
    "admin.printInvoice": "Stampa fattura",
    "admin.invoiceGenerated": "Fattura generata con successo",
    "admin.downloadFormat": "Formato download",
    
    // Admin Users Page
    "admin.userDetails": "Dettagli utente",
    "admin.username": "Nome utente",
    "admin.email": "Email",
    "admin.password": "Password",
    "admin.firstName": "Nome",
    "admin.lastName": "Cognome",
    "admin.address": "Indirizzo",
    "admin.city": "Città",
    "admin.postalCode": "Codice postale",
    "admin.country": "Paese",
    "admin.phone": "Telefono",
    "admin.role": "Ruolo",
    "admin.lastLogin": "Ultimo accesso",
    "admin.resetPassword": "Reimposta password",
    "admin.userSaved": "Utente salvato con successo",
    "admin.userDeleted": "Utente eliminato con successo",
    
    // Admin Settings Page
    "admin.generalSettings": "Impostazioni generali",
    "admin.shopName": "Nome negozio",
    "admin.shopLogo": "Logo negozio",
    "admin.currency": "Valuta",
    "admin.language": "Lingua",
    "admin.taxRate": "Aliquota fiscale",
    "admin.contactEmail": "Email di contatto",
    "admin.contactPhone": "Telefono di contatto",
    "admin.businessAddress": "Indirizzo aziendale",
    "admin.socialLinks": "Link social media",
    "admin.metaTitle": "Meta titolo",
    "admin.metaDescription": "Meta descrizione",
    "admin.favicon": "Favicon",
    "admin.settingsSaved": "Impostazioni salvate con successo",
    
    // Document Management
    "admin.uploadDocument": "Carica documento",
    "admin.documentName": "Nome documento",
    "admin.documentType": "Tipo documento",
    "admin.documentSize": "Dimensione documento",
    "admin.documentDescription": "Descrizione documento",
    "admin.documentUploaded": "Documento caricato con successo",
    "admin.documentDeleted": "Documento eliminato con successo",
    "admin.download": "Scarica",

    // Pagina iniziale
    "home.featured": "Prodotti in evidenza",
    "home.collections": "Collezioni",
    "home.welcome": "Benvenuti a Kerzenwelt by Dani",
    "home.subtitle": "Candele artigianali con ingredienti naturali",
    "home.shopNow": "Acquista ora",
    "home.categories": "Le nostre categorie",
    "home.categoriesSubtitle":
      "Esplora la nostra ricca selezione di candele fatte a mano per ogni occasione",
    "home.heroTitle": "Candele artigianali per momenti speciali",
    "home.heroSubtitle":
      "Scopri la nostra collezione di candele profumate premium realizzate con amore",
    "home.exploreCollection": "Esplora la collezione",
    "home.aboutUs": "Chi siamo",
    "home.featuredSubtitle":
      "I nostri prodotti più popolari che i nostri clienti amano",
    "home.viewAllProducts": "Vedi tutti i prodotti",
    "home.errorLoading":
      "Si è verificato un errore durante il caricamento dei prodotti.",
    "home.ourStory": "La nostra storia",
    "home.storyDescription":
      "Ogni nostra candela è realizzata con cura e amore, prestando attenzione a ogni dettaglio - dalla selezione delle migliori fragranze alla rifinitura dell'aspetto estetico. Siamo orgogliosi del nostro artigianato e della passione con cui affrontiamo ogni prodotto.",
    "home.naturalIngredients": "Ingredienti naturali",
    "home.naturalIngredientsDesc":
      "Utilizziamo solo cera di soia naturale e oli essenziali",
    "home.handmade": "Fatto a mano",
    "home.handmadeDesc": "Ogni candela è realizzata con cura e artigianalmente",
    "home.sustainability": "Sostenibilità",
    "home.sustainabilityDesc": "Imballaggi e materiali ecologici",
    "home.homeComfort": "Comfort domestico",
    "home.homeComfortDesc": "Crea un'atmosfera accogliente nel tuo spazio",
    "home.learnMore": "Scopri di più su di noi",
    "home.autumnCollection": "Collezione Autunno",
    "home.autumnCollectionDesc":
      "Scopri la nostra nuova collezione di fragranze autunnali. Profumi caldi e piacevoli che riempiranno la tua casa con un senso di comfort e calore durante le giornate più fresche.",
    "home.loading": "Caricamento...",
    "home.noProducts":
      "Non sono ancora stati aggiunti prodotti a questa collezione.",
    "home.viewCollection": "Visualizza collezione",

    // Prodotti
    "product.addToCart": "Aggiungi al carrello",
    "product.selectScent": "Seleziona profumo",
    "product.selectColor": "Seleziona colore",
    "product.outOfStock": "Esaurito",
    "product.dimensions": "Dimensioni",
    "product.weight": "Peso",
    "product.burnTime": "Tempo di combustione",
    "product.materials": "Materiali",
    "product.instructions": "Istruzioni",
    "product.maintenance": "Manutenzione",

    // Carrello
    "cart.title": "Il tuo carrello",
    "cart.empty": "Il tuo carrello è vuoto",
    "cart.continue": "Continua lo shopping",
    "cart.checkout": "Procedi all'acquisto",
    "cart.total": "Totale",
    "cart.remove": "Rimuovi",

    // Piè di pagina
    "footer.about": "Chi è Kerzenwelt by Dani",
    "footer.about.text":
      "Candele artigianali con ingredienti naturali. Dalla nostra famiglia alla tua casa.",
    "footer.quickLinks": "Link rapidi",
    "footer.customerSupport": "Assistenza clienti",
    "footer.contact": "Contatti",
    "footer.followUs": "Seguici",
    "footer.copyright": "Tutti i diritti riservati.",
    "footer.tagline":
      "Candele artigianali con ingredienti naturali. Dalla nostra famiglia alla tua casa.",
    "footer.myAccount": "Il mio account",
    "footer.paymentMethods": "Metodi di pagamento",

    // Testimonials
    "testimonials.title": "Cosa dicono i nostri clienti",
    "testimonials.subtitle": "Esperienze dei nostri clienti soddisfatti",
    "testimonials.empty":
      "Non abbiamo ancora recensioni. Sii il primo a condividere la tua esperienza!",
    "testimonials.browseProducts":
      "Sfoglia i prodotti e aggiungi una recensione",
    "testimonials.loginToReview": "Accedi e aggiungi una recensione",

    // Dialog components
    "dialog.areYouSure": "Sei sicuro?",
    "dialog.cannotUndo": "Questa azione non può essere annullata.",
    "dialog.delete": "Elimina",
    "dialog.cancel": "Annulla",
    "dialog.confirm": "Conferma",

    // Newsletter
    "newsletter.title": "Iscriviti alla nostra newsletter",
    "newsletter.description":
      "Sii il primo a conoscere i nostri nuovi prodotti, offerte speciali e sconti. Iscriviti alla nostra newsletter e ottieni il 10% di sconto sul tuo primo ordine.",
    "newsletter.placeholder": "Il tuo indirizzo email",
    "newsletter.button": "Iscriviti",
    "newsletter.loading": "Caricamento...",
    "newsletter.privacy":
      "Non condivideremo mai i tuoi dati con terze parti. Puoi cancellarti in qualsiasi momento.",
    "newsletter.success":
      "Grazie per l'iscrizione! Riceverai presto la nostra newsletter.",
    "newsletter.error": "Per favore inserisci il tuo indirizzo email.",
    
    // Admin panel
    "admin.backToStore": "Torna al negozio",
  },

  sl: {
    // Splošni admin elementi
    "admin.general.uploading": "Nalaganje...",
    "admin.product.preview": "Predogled",
    
    // Navigacija
    "nav.home": "Domov",
    "nav.products": "Izdelki",
    "nav.about": "O nas",
    "nav.contact": "Kontakt",
    "nav.cart": "Košarica",
    "nav.login": "Prijava",
    "nav.account": "Moj račun",
    "nav.admin": "Administracija",
    "nav.logout": "Odjava",
    "nav.allCategories": "Vse kategorije",
    "nav.loadingCategories": "Nalaganje kategorij...",
    "nav.pictures": "Slike",

    // Admin meni
    "admin.dashboard": "Nadzorna plošča",
    "admin.products": "Izdelki",
    "admin.categories": "Kategorije",
    "admin.scents": "Dišave",
    "admin.colors": "Barve",
    "admin.collections": "Kolekcije",
    "admin.orders": "Naročila",
    "admin.invoices": "Računi",
    "admin.users": "Uporabniki",
    "admin.payments": "Plačila",
    "admin.panel": "Kerzenwelt Admin",
    "admin.delivery": "Nastavitve dostave",
    "admin.settings": "Nastavitve",
    "admin.pageSettings": "Nastavitve strani",
    "admin.contactSettings": "Kontaktne nastavitve",
    "admin.documents": "Dokumenti podjetja",
    "admin.notifications": "Obvestila",
    "admin.newOrder": "Novo naročilo",
    "admin.statistics": "Statistika",
    "admin.visits": "Obiski strani",
    "admin.addNew": "Dodaj novo",
    "admin.edit": "Uredi",
    "admin.delete": "Izbriši",
    "admin.save": "Shrani",
    "admin.cancel": "Prekliči",
    "admin.actions": "Dejanja",
    "admin.status": "Status",
    "admin.active": "Aktivno",
    "admin.inactive": "Neaktivno",
    "admin.selectLanguage": "Izberi jezik",
    
    // Admin Common Elements
    "admin.id": "ID",
    "admin.name": "Ime",
    "admin.description": "Opis",
    "admin.image": "Slika",
    "admin.price": "Cena",
    "admin.stock": "Zaloga",
    "admin.featured": "Izpostavljeno",
    "admin.category": "Kategorija",
    "admin.createdAt": "Ustvarjeno",
    "admin.updatedAt": "Posodobljeno",
    "admin.search": "Iskanje",
    "admin.filter": "Filter",
    "admin.confirm": "Potrdi",
    "admin.customer": "Stranka",
    "admin.date": "Datum",
    "admin.total": "Skupaj",
    "admin.quantity": "Količina",
    "admin.payment": "Plačilo",
    "admin.confirmDelete": "Potrdi brisanje",
    "admin.deleteWarning": "Ali ste prepričani, da želite izbrisati ta element? Tega dejanja ni mogoče razveljaviti.",
    
    // Admin Product Page
    "admin.productDetails": "Podrobnosti izdelka",
    "admin.productName": "Ime izdelka",
    "admin.productDescription": "Opis izdelka",
    "admin.productImage": "Slika izdelka",
    "admin.productPrice": "Cena izdelka",
    "admin.productStock": "Zaloga izdelka",
    "admin.productCategory": "Kategorija izdelka",
    "admin.productActive": "Izdelek aktiven",
    "admin.productFeatured": "Izdelek izpostavljen",
    "admin.productScents": "Dišave izdelka",
    "admin.productColors": "Barve izdelka",
    "admin.productDimensions": "Dimenzije izdelka",
    "admin.productWeight": "Teža izdelka",
    "admin.productMaterials": "Materiali izdelka",
    "admin.productUsage": "Uporaba izdelka",
    "admin.productMaintenance": "Vzdrževanje izdelka",
    "admin.uploadImage": "Naloži sliko",
    "admin.noScentsSelected": "Ni izbranih dišav",
    "admin.noColorsSelected": "Ni izbranih barv",
    "admin.chooseScents": "Izberi dišave",
    "admin.chooseColors": "Izberi barve",
    "admin.productSaved": "Izdelek uspešno shranjen",
    "admin.productDeleted": "Izdelek uspešno izbrisan",
    "admin.product.featuredProduct": "Izpostavljeno na domači strani",
    "admin.product.productActive": "Izdelek aktiven",
    "admin.product.productActiveHint": "(Če je onemogočeno, izdelek ne bo viden strankam)",
    "admin.product.saveChanges": "Shrani spremembe",
    "admin.product.createProduct": "Ustvari izdelek",
    "admin.product.cancel": "Prekliči",
    "admin.product.image": "Slika izdelka",
    "admin.product.url": "URL",
    "admin.product.upload": "Naloži",
    "admin.product.imageUrlPlaceholder": "https://primer.com/slika.jpg",
    "admin.product.imageUrlDescription": "Vnesite URL do slike",
    "admin.product.clickToUpload": "Kliknite za nalaganje",
    "admin.product.imageFormats": "JPG, PNG, GIF do 5MB",
    "admin.product.imageResizeInfo": "Slike bodo samodejno pomanjšane na 800x800px",
    "admin.product.imageLoadingError": "Napaka pri nalaganju slike",
    "admin.product.price": "Cena",
    "admin.product.pricePlaceholder": "Vnesite ceno",
    "admin.product.stock": "Zaloga",
    "admin.product.stockPlaceholder": "Vnesite količino na zalogi",
    "admin.product.description": "Opis",
    "admin.product.descriptionPlaceholder": "Vnesite opis izdelka",
    "admin.product.name": "Ime",
    "admin.product.namePlaceholder": "Vnesite ime izdelka",
    "admin.product.dimensions": "Dimenzije",
    "admin.product.dimensionsPlaceholder": "npr. 10 x 5 x 3 cm",
    "admin.product.weight": "Teža",
    "admin.product.weightPlaceholder": "npr. 250 g",
    "admin.product.materials": "Materiali",
    "admin.product.materialsPlaceholder": "npr. Sojin vosek, bombažni stenj",
    "admin.product.usage": "Uporaba",
    "admin.product.usagePlaceholder": "Navodila za uporabo",
    "admin.product.maintenance": "Vzdrževanje",
    "admin.product.maintenancePlaceholder": "Navodila za vzdrževanje",
    "admin.product.availableScents": "Razpoložljive dišave",
    "admin.product.selectScents": "Izberite dišave, ki bodo na voljo za ta izdelek",
    "admin.product.loadingScents": "Nalaganje dišav...",
    "admin.product.availableColors": "Razpoložljive barve",
    "admin.product.selectColors": "Izberite barve, ki bodo na voljo za ta izdelek",
    "admin.product.loadingColors": "Nalaganje barv...",
    "admin.product.enableColorSelection": "Omogoči izbiro barv",
    "admin.product.enableMultipleColors": "Omogoči izbiro več barv",
    "admin.product.imagePreview": "Predogled slike",
    "admin.product.category": "Kategorija",
    "admin.product.burnTime": "Čas gorenja",
    "admin.product.instructions": "Navodila",
    "admin.productsTitle": "Izdelki",
    "admin.productsSubtitle": "Upravljanje izdelkov v trgovini",
    "admin.productsList": "Seznam izdelkov",
    "admin.productsCount": "izdelkov",
    "admin.product.imageColumn": "Slika",
    "admin.product.nameColumn": "Ime",
    "admin.product.categoryColumn": "Kategorija",
    "admin.product.priceColumn": "Cena",
    "admin.product.stockColumn": "Zaloga",
    "admin.product.statusColumn": "Status",
    "admin.product.actionsColumn": "Dejanja",
    "admin.product.inStock": "Na zalogi",
    "admin.product.active": "Aktiven",
    
    // Admin Orders Page
    "admin.orderDetails": "Podrobnosti naročila",
    "admin.orderNumber": "Številka naročila",
    "admin.orderDate": "Datum naročila",
    "admin.orderStatus": "Status naročila",
    "admin.orderTotal": "Skupna vrednost naročila",
    "admin.orderItems": "Postavke naročila",
    "admin.orderCustomer": "Stranka",
    "admin.orderPayment": "Način plačila",
    "admin.orderShipping": "Naslov za dostavo",
    "admin.orderBilling": "Naslov za račun",
    "admin.orderNotes": "Opombe",
    "admin.updateOrderStatus": "Posodobi status naročila",
    "admin.generateInvoice": "Ustvari račun",
    "admin.pending": "V čakanju",
    "admin.processing": "V obdelavi",
    "admin.shipped": "Poslano",
    "admin.delivered": "Dostavljeno",
    "admin.cancelled": "Preklicano",
    "admin.statusUpdated": "Status uspešno posodobljen",
    
    // Admin Invoice Page
    "admin.invoiceDetails": "Podrobnosti računa",
    "admin.invoiceNumber": "Številka računa",
    "admin.invoiceDate": "Datum računa",
    "admin.invoiceItems": "Postavke računa",
    "admin.subtotal": "Vmesni znesek",
    "admin.tax": "Davek",
    "admin.taxNumber": "Davčna številka",
    "admin.downloadInvoice": "Prenesi račun",
    "admin.printInvoice": "Natisni račun",
    "admin.invoiceGenerated": "Račun uspešno ustvarjen",
    "admin.downloadFormat": "Format za prenos",
    
    // Admin Users Page
    "admin.userDetails": "Podrobnosti uporabnika",
    "admin.username": "Uporabniško ime",
    "admin.email": "E-pošta",
    "admin.password": "Geslo",
    "admin.firstName": "Ime",
    "admin.lastName": "Priimek",
    "admin.address": "Naslov",
    "admin.city": "Mesto",
    "admin.postalCode": "Poštna številka",
    "admin.country": "Država",
    "admin.phone": "Telefon",
    "admin.role": "Vloga",
    "admin.lastLogin": "Zadnja prijava",
    "admin.resetPassword": "Ponastavi geslo",
    "admin.userSaved": "Uporabnik uspešno shranjen",
    "admin.userDeleted": "Uporabnik uspešno izbrisan",
    
    // Admin Settings Page
    "admin.generalSettings": "Splošne nastavitve",
    "admin.shopName": "Ime trgovine",
    "admin.shopLogo": "Logotip trgovine",
    "admin.currency": "Valuta",
    "admin.language": "Jezik",
    "admin.taxRate": "Davčna stopnja",
    "admin.contactEmail": "Kontaktni e-naslov",
    "admin.contactPhone": "Kontaktni telefon",
    "admin.businessAddress": "Poslovni naslov",
    "admin.socialLinks": "Družbena omrežja",
    "admin.metaTitle": "Meta naslov",
    "admin.metaDescription": "Meta opis",
    "admin.favicon": "Favicon",
    "admin.settingsSaved": "Nastavitve uspešno shranjene",
    
    // Document Management
    "admin.uploadDocument": "Naloži dokument",
    "admin.documentName": "Ime dokumenta",
    "admin.documentType": "Vrsta dokumenta",
    "admin.documentSize": "Velikost dokumenta",
    "admin.documentDescription": "Opis dokumenta",
    "admin.documentUploaded": "Dokument uspešno naložen",
    "admin.documentDeleted": "Dokument uspešno izbrisan",
    "admin.download": "Prenesi",

    // Domača stran
    "home.featured": "Izpostavljeni izdelki",
    "home.collections": "Kolekcije",
    "home.welcome": "Dobrodošli v Kerzenwelt by Dani",
    "home.subtitle": "Ročno izdelane sveče iz naravnih sestavin",
    "home.shopNow": "Nakupujte zdaj",
    "home.categories": "Naše kategorije",
    "home.categoriesSubtitle":
      "Raziščite našo bogato izbiro ročno izdelanih sveč za vsako priložnost",
    "home.heroTitle": "Ročno izdelane sveče za posebne trenutke",
    "home.heroSubtitle":
      "Odkrijte našo kolekcijo vrhunskih dišečih sveč, narejenih z ljubeznijo",
    "home.exploreCollection": "Raziščite kolekcijo",
    "home.aboutUs": "O nas",
    "home.featuredSubtitle":
      "Naši najbolj priljubljeni izdelki, ki jih naše stranke obožujejo",
    "home.viewAllProducts": "Oglejte si vse izdelke",
    "home.errorLoading": "Pri nalaganju izdelkov je prišlo do napake.",
    "home.ourStory": "Naša zgodba",
    "home.storyDescription":
      "Vsaka naša sveča je izdelana s skrbjo in ljubeznijo, s pozornostjo na vsako podrobnost - od izbire najboljših dišav do končnega estetskega videza. Ponosni smo na naše rokodelstvo in strast, s katero pristopamo k vsakemu izdelku.",
    "home.naturalIngredients": "Naravne sestavine",
    "home.naturalIngredientsDesc":
      "Uporabljamo samo naravni sojin vosek in eterična olja",
    "home.handmade": "Ročno izdelano",
    "home.handmadeDesc": "Vsaka sveča je skrbno in ročno izdelana",
    "home.sustainability": "Trajnostnost",
    "home.sustainabilityDesc": "Okolju prijazna embalaža in materiali",
    "home.homeComfort": "Udobje doma",
    "home.homeComfortDesc": "Ustvarite prijetno vzdušje v vašem prostoru",
    "home.learnMore": "Več o nas",
    "home.autumnCollection": "Jesenska kolekcija",
    "home.autumnCollectionDesc":
      "Odkrijte našo novo kolekcijo jesenskih dišav. Tople in prijetne dišave, ki bodo vaš dom v hladnejših dneh napolnile z občutkom udobja in topline.",
    "home.loading": "Nalaganje...",
    "home.noProducts": "V to kolekcijo še ni bilo dodanih izdelkov.",
    "home.viewCollection": "Oglejte si kolekcijo",

    // Izdelki
    "product.addToCart": "Dodaj v košarico",
    "product.selectScent": "Izberite vonj",
    "product.selectColor": "Izberite barvo",
    "product.outOfStock": "Ni na zalogi",
    "product.dimensions": "Dimenzije",
    "product.weight": "Teža",
    "product.burnTime": "Čas gorenja",
    "product.materials": "Materiali",
    "product.instructions": "Navodila za uporabo",
    "product.maintenance": "Vzdrževanje",

    // Košarica
    "cart.title": "Vaša košarica",
    "cart.empty": "Vaša košarica je prazna",
    "cart.continue": "Nadaljujte z nakupovanjem",
    "cart.checkout": "Zaključi naročilo",
    "cart.total": "Skupaj",
    "cart.remove": "Odstrani",

    // Noga strani
    "footer.about": "O Kerzenwelt by Dani",
    "footer.about.text":
      "Ročno izdelane sveče iz naravnih sestavin. Od naše družine do vašega doma.",
    "footer.quickLinks": "Hitre povezave",
    "footer.customerSupport": "Podpora strankam",
    "footer.contact": "Kontakt",
    "footer.followUs": "Sledite nam",
    "footer.copyright": "Vse pravice pridržane.",
    "footer.tagline":
      "Ročno izdelane sveče iz naravnih sestavin. Od naše družine do vašega doma.",
    "footer.myAccount": "Moj račun",
    "footer.paymentMethods": "Načini plačila",

    // Testimonials
    "testimonials.title": "Kaj pravijo naše stranke",
    "testimonials.subtitle": "Izkušnje naših zadovoljnih strank",
    "testimonials.empty":
      "Trenutno nimamo ocen. Bodite prvi, ki bo delil svojo izkušnjo!",
    "testimonials.browseProducts": "Preglejte izdelke in dodajte oceno",
    "testimonials.loginToReview": "Prijavite se in dodajte oceno",

    // Dialog components
    "dialog.areYouSure": "Ali ste prepričani?",
    "dialog.cannotUndo": "Te akcije ni mogoče razveljaviti.",
    "dialog.delete": "Izbriši",
    "dialog.cancel": "Prekliči",
    "dialog.confirm": "Potrdi",

    // Newsletter
    "newsletter.title": "Naročite se na naše novice",
    "newsletter.description":
      "Bodite prvi, ki bo izvedel za naše nove izdelke, posebne ponudbe in popuste. Naročite se na naše novice in dobite 10% popust na vaše prvo naročilo.",
    "newsletter.placeholder": "Vaš e-poštni naslov",
    "newsletter.button": "Naroči se",
    "newsletter.loading": "Nalaganje...",
    "newsletter.privacy":
      "Vaših podatkov nikoli ne bomo delili s tretjimi osebami. Odjava je mogoča kadarkoli.",
    "newsletter.success": "Hvala za prijavo! Kmalu boste prejeli naše novice.",
    "newsletter.error": "Prosimo, vnesite vaš e-poštni naslov.",
    
    // Admin panel
    "admin.backToStore": "Nazaj v trgovino",
  },
};

// Imena jezika za prikaz u izborniku
export const languageNames: Record<Language, string> = {
  de: "Deutsch",
  hr: "Hrvatski",
  en: "English",
  it: "Italiano",
  sl: "Slovensko",
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
  translateText: (text: string, sourceLanguage?: Language) => string;
  translateObject: <T extends Record<string, any>>(
    obj: T,
    sourceLanguage?: Language,
  ) => T;
  translateArray: <T extends Record<string, any>>(
    array: T[],
    sourceLanguage?: Language,
  ) => T[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);

// Funkcija za primjenu jezika na HTML element
function applyLanguage(language: Language) {
  if (typeof window !== "undefined") {
    document.documentElement.lang = language;
  }
}

// Dohvati početni jezik iz localStorage
function getInitialLanguage(): Language {
  if (typeof window === "undefined") return "de"; // Zadani jezik je njemački

  const savedLanguage = localStorage.getItem("language") as Language;
  return savedLanguage && ["de", "hr", "en", "it", "sl"].includes(savedLanguage)
    ? savedLanguage
    : "de"; // Zadani jezik je njemački
}

import {
  translateArray,
  translateObject,
  translateText as translateTextService,
} from "@/lib/translation-service";

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (newLanguage: Language) => {
    localStorage.setItem("language", newLanguage);
    setLanguageState(newLanguage);
    applyLanguage(newLanguage);
  };

  // Funkcija za prijevod
  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  // Funkcija za prevođenje teksta
  const translateText = (text: string, sourceLanguage?: Language): string => {
    return translateTextService(text, language, sourceLanguage);
  };

  // Inicijalno postavi jezik
  useEffect(() => {
    applyLanguage(language);
  }, [language]);

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        translateText,
        translateObject: (obj, sourceLanguage) =>
          translateObject(obj, language, sourceLanguage),
        translateArray: (array, sourceLanguage) =>
          translateArray(array, language, sourceLanguage),
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
